-- Shades World uppercase MySQL 8 DDL and DML for the Spring configuration.
-- Requires PhysicalNamingStrategyStandardImpl so Hibernate preserves @Table names.
-- Run against a fresh/empty Aiven defaultdb. Does not drop or create the database.

-- ============================================================================================
-- Aiven defaultdb bootstrap â€” run ONCE before the first start against the cloud database.
-- Generated 2026-08-12 from the live, fully-migrated local schema (ECOMMERCE_DB), which the
-- application validates at startup (ddl-auto=validate): an empty defaultdb fails boot with
-- "Schema-validation: missing table" until this has been applied.
--
-- HOW TO RUN (password prompted, never on the command line in history):
--   mysql -h mysql-71d4591-dklord2469-9770.l.aivencloud.com -P 28303 -u avnadmin -p \
--         --ssl-mode=REQUIRED -D defaultdb < database/aiven-defaultdb-bootstrap.sql
--   then, for tax/config reference rows (idempotent):
--   mysql ... -D defaultdb < src/main/resources/data.sql
--
-- Contents: all 42 tables (CREATE TABLE IF NOT EXISTS, no DROPs anywhere) plus the seed data
-- the application needs: 4 ROLES, 12 PERMISSIONS, 25 ROLE_PERMISSIONS, the 4 storefront
-- CATEGORIES, and the existing USERS with their USER_ROLES â€” including the ADMIN mapping for
-- admin@example.com (BCrypt hashes copied verbatim, so existing passwords keep working).
-- Safe to run repeatedly: every statement is IF NOT EXISTS / INSERT IGNORE.
-- ============================================================================================


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ADDRESSES` (
  `ADDRESS_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `ADDRESS_TYPE` varchar(20) DEFAULT 'SHIPPING',
  `RECIPIENT_NAME` varchar(255) NOT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `HOUSE_NUMBER` varchar(50) DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(255) NOT NULL,
  `ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `CITY` varchar(100) NOT NULL,
  `STATE` varchar(100) NOT NULL,
  `PINCODE` varchar(20) NOT NULL,
  `COUNTRY` varchar(100) NOT NULL,
  `IS_DEFAULT` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VERSION` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `IDX_ADDRESSES_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_ADDRESS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_ADDRESS_TYPE` CHECK ((`ADDRESS_TYPE` in (_utf8mb4'SHIPPING',_utf8mb4'BILLING',_utf8mb4'BOTH')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `AUDIT_LOGS` (
  `AUDIT_LOG_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint DEFAULT NULL,
  `ACTION_TYPE` varchar(100) NOT NULL,
  `ENTITY_TYPE` varchar(100) NOT NULL,
  `ENTITY_ID` bigint DEFAULT NULL,
  `OLD_VALUE` json DEFAULT NULL,
  `NEW_VALUE` json DEFAULT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUDIT_LOG_ID`),
  KEY `IDX_AUDIT_ENTITY` (`ENTITY_TYPE`,`ENTITY_ID`),
  KEY `IDX_AUDIT_USER` (`USER_ID`),
  KEY `IDX_AUDIT_CREATED_AT` (`CREATED_AT`),
  CONSTRAINT `FK_AUDIT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `AUTOMATIC_OFFER_CATEGORIES` (
  `AUTOMATIC_OFFER_ID` bigint NOT NULL,
  `CATEGORY_ID` bigint NOT NULL,
  PRIMARY KEY (`AUTOMATIC_OFFER_ID`,`CATEGORY_ID`),
  KEY `FK_AUTOMATIC_OFFER_CATEGORY_CATEGORY` (`CATEGORY_ID`),
  CONSTRAINT `FK_AUTOMATIC_OFFER_CATEGORY_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORIES` (`CATEGORY_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_AUTOMATIC_OFFER_CATEGORY_OFFER` FOREIGN KEY (`AUTOMATIC_OFFER_ID`) REFERENCES `AUTOMATIC_OFFERS` (`AUTOMATIC_OFFER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `AUTOMATIC_OFFER_PRODUCTS` (
  `AUTOMATIC_OFFER_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  PRIMARY KEY (`AUTOMATIC_OFFER_ID`,`PRODUCT_ID`),
  KEY `FK_AUTOMATIC_OFFER_PRODUCT_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_AUTOMATIC_OFFER_PRODUCT_OFFER` FOREIGN KEY (`AUTOMATIC_OFFER_ID`) REFERENCES `AUTOMATIC_OFFERS` (`AUTOMATIC_OFFER_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_AUTOMATIC_OFFER_PRODUCT_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `AUTOMATIC_OFFERS` (
  `AUTOMATIC_OFFER_ID` bigint NOT NULL AUTO_INCREMENT,
  `OFFER_NAME` varchar(120) NOT NULL,
  `BANNER_MESSAGE` varchar(300) DEFAULT NULL,
  `REQUIRED_QUANTITY` int NOT NULL,
  `DISCOUNT_PER_GROUP` decimal(12,2) NOT NULL,
  `MINIMUM_ORDER_SUBTOTAL` decimal(12,2) NOT NULL DEFAULT '0.00',
  `SCOPE_TYPE` varchar(24) NOT NULL DEFAULT 'ALL_PRODUCTS',
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '0',
  `STARTS_AT` datetime NOT NULL,
  `ENDS_AT` datetime NOT NULL,
  `PRIORITY` int NOT NULL DEFAULT '0',
  `VERSION` bigint NOT NULL DEFAULT '0',
  `ARCHIVED_AT` datetime DEFAULT NULL,
  `CREATED_BY_USER_ID` bigint DEFAULT NULL,
  `UPDATED_BY_USER_ID` bigint DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ACTIVE_SINGLETON` tinyint(1) GENERATED ALWAYS AS (if(((`IS_ACTIVE` = 1) and (`ARCHIVED_AT` is null)),1,NULL)) STORED,
  PRIMARY KEY (`AUTOMATIC_OFFER_ID`),
  UNIQUE KEY `UQ_AUTOMATIC_OFFER_ACTIVE` (`ACTIVE_SINGLETON`),
  KEY `IDX_AUTOMATIC_OFFERS_EFFECTIVE` (`IS_ACTIVE`,`STARTS_AT`,`ENDS_AT`),
  KEY `FK_AUTOMATIC_OFFER_CREATED_BY` (`CREATED_BY_USER_ID`),
  KEY `FK_AUTOMATIC_OFFER_UPDATED_BY` (`UPDATED_BY_USER_ID`),
  CONSTRAINT `FK_AUTOMATIC_OFFER_CREATED_BY` FOREIGN KEY (`CREATED_BY_USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_AUTOMATIC_OFFER_UPDATED_BY` FOREIGN KEY (`UPDATED_BY_USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_AUTOMATIC_OFFER_DISCOUNT` CHECK ((`DISCOUNT_PER_GROUP` > 0)),
  CONSTRAINT `CHK_AUTOMATIC_OFFER_MINIMUM` CHECK ((`MINIMUM_ORDER_SUBTOTAL` >= 0)),
  CONSTRAINT `CHK_AUTOMATIC_OFFER_REQUIRED_QUANTITY` CHECK ((`REQUIRED_QUANTITY` >= 2)),
  CONSTRAINT `CHK_AUTOMATIC_OFFER_SCOPE` CHECK ((`SCOPE_TYPE` in (_cp850'ALL_PRODUCTS',_cp850'SELECTED_PRODUCTS',_cp850'SELECTED_CATEGORIES'))),
  CONSTRAINT `CHK_AUTOMATIC_OFFER_WINDOW` CHECK ((`ENDS_AT` > `STARTS_AT`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `CART_ITEMS` (
  `CART_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `CART_ID` bigint NOT NULL,
  `VARIANT_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL,
  `ADDED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_ITEM_ID`),
  UNIQUE KEY `UQ_CART_VARIANT` (`CART_ID`,`VARIANT_ID`),
  KEY `FK_CART_ITEM_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_CART_ITEM_CART` FOREIGN KEY (`CART_ID`) REFERENCES `CARTS` (`CART_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_CART_ITEM_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANTS` (`VARIANT_ID`),
  CONSTRAINT `CHK_CART_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `CARTS` (
  `CART_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `CART_STATUS` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_ID`),
  KEY `IDX_CARTS_USER_STATUS` (`USER_ID`,`CART_STATUS`),
  CONSTRAINT `FK_CART_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_CART_STATUS` CHECK ((`CART_STATUS` in (_utf8mb4'ACTIVE',_utf8mb4'ORDERED',_utf8mb4'ABANDONED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `CATEGORIES` (
  `CATEGORY_ID` bigint NOT NULL AUTO_INCREMENT,
  `PARENT_CATEGORY_ID` bigint DEFAULT NULL,
  `CATEGORY_NAME` varchar(150) NOT NULL,
  `DESCRIPTION` text,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATEGORY_ID`),
  UNIQUE KEY `UQ_CATEGORY_NAME` (`CATEGORY_NAME`),
  KEY `FK_CATEGORY_PARENT` (`PARENT_CATEGORY_ID`),
  CONSTRAINT `FK_CATEGORY_PARENT` FOREIGN KEY (`PARENT_CATEGORY_ID`) REFERENCES `CATEGORIES` (`CATEGORY_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `CONFIG` (
  `CONFIG_ID` bigint NOT NULL AUTO_INCREMENT,
  `CONFIG_SHORT_CODE` varchar(100) NOT NULL,
  `CONFIG_VALUE` text,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CONFIG_ID`),
  UNIQUE KEY `UQ_CONFIG_SHORT_CODE` (`CONFIG_SHORT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `COUPON_USAGE` (
  `COUPON_USAGE_ID` bigint NOT NULL AUTO_INCREMENT,
  `COUPON_ID` bigint NOT NULL,
  `USER_ID` bigint NOT NULL,
  `ORDER_ID` bigint NOT NULL,
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL,
  `USED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`COUPON_USAGE_ID`),
  UNIQUE KEY `UQ_COUPON_ORDER` (`COUPON_ID`,`ORDER_ID`),
  KEY `FK_COUPON_USAGE_ORDER` (`ORDER_ID`),
  KEY `IDX_COUPON_USAGE_USER` (`USER_ID`),
  CONSTRAINT `FK_COUPON_USAGE_COUPON` FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPONS` (`COUPON_ID`),
  CONSTRAINT `FK_COUPON_USAGE_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  CONSTRAINT `FK_COUPON_USAGE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
  CONSTRAINT `CHK_COUPON_USAGE_AMOUNT` CHECK ((`DISCOUNT_AMOUNT` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `COUPONS` (
  `COUPON_ID` bigint NOT NULL AUTO_INCREMENT,
  `COUPON_CODE` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DISCOUNT_TYPE` varchar(20) NOT NULL,
  `DISCOUNT_VALUE` decimal(12,2) NOT NULL,
  `MINIMUM_ORDER_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `MAXIMUM_DISCOUNT_AMOUNT` decimal(12,2) DEFAULT NULL,
  `USAGE_LIMIT` int DEFAULT NULL,
  `USAGE_LIMIT_PER_USER` int DEFAULT NULL,
  `VALID_FROM` datetime NOT NULL,
  `VALID_TO` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `UQ_COUPON_CODE` (`COUPON_CODE`),
  CONSTRAINT `CHK_COUPON_DATES` CHECK ((`VALID_TO` > `VALID_FROM`)),
  CONSTRAINT `CHK_COUPON_MINIMUM_AMOUNT` CHECK ((`MINIMUM_ORDER_AMOUNT` >= 0)),
  CONSTRAINT `CHK_COUPON_TYPE` CHECK ((`DISCOUNT_TYPE` in (_cp850'PERCENTAGE',_cp850'FIXED',_cp850'PAIR_FIXED'))),
  CONSTRAINT `CHK_COUPON_VALUE` CHECK ((`DISCOUNT_VALUE` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `CUSTOMER_COMMUNICATION_PREFERENCES` (
  `USER_ID` bigint NOT NULL,
  `EMAIL_ORDER_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `EMAIL_SHIPMENT_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `EMAIL_RETURN_REFUND_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_ORDER_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_SHIPMENT_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_RETURN_REFUND_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `IN_APP_REVIEW_UPDATES` tinyint(1) NOT NULL DEFAULT '1',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_COMMUNICATION_PREFERENCES_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `EMAIL_OUTBOX` (
  `EMAIL_OUTBOX_ID` bigint NOT NULL AUTO_INCREMENT,
  `RECIPIENT` varchar(255) NOT NULL,
  `SUBJECT` varchar(255) NOT NULL,
  `BODY` text NOT NULL,
  `STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `ATTEMPT_COUNT` int NOT NULL DEFAULT '0',
  `NEXT_ATTEMPT_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_ERROR` varchar(1000) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SENT_AT` datetime DEFAULT NULL,
  `EXPIRES_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`EMAIL_OUTBOX_ID`),
  KEY `IDX_EMAIL_OUTBOX_DUE` (`STATUS`,`NEXT_ATTEMPT_AT`,`CREATED_AT`),
  CONSTRAINT `CHK_EMAIL_OUTBOX_ATTEMPTS` CHECK ((`ATTEMPT_COUNT` >= 0)),
  CONSTRAINT `CHK_EMAIL_OUTBOX_STATUS` CHECK ((`STATUS` in (_utf8mb4'PENDING',_utf8mb4'RETRY',_utf8mb4'SENT',_utf8mb4'FAILED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `EMAIL_VERIFICATION_TOKENS` (
  `EMAIL_VERIFICATION_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `VERIFIED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EMAIL_VERIFICATION_TOKEN_ID`),
  UNIQUE KEY `UQ_EMAIL_VERIFICATION_TOKEN` (`TOKEN_HASH`),
  KEY `FK_EMAIL_VERIFICATION_USER` (`USER_ID`),
  CONSTRAINT `FK_EMAIL_VERIFICATION_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `INVENTORY_MOVEMENTS` (
  `INVENTORY_MOVEMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `VARIANT_ID` bigint NOT NULL,
  `MOVEMENT_TYPE` varchar(30) NOT NULL,
  `QUANTITY_CHANGE` int NOT NULL,
  `REFERENCE_TYPE` varchar(50) DEFAULT NULL,
  `REFERENCE_ID` bigint DEFAULT NULL,
  `NOTES` varchar(500) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`INVENTORY_MOVEMENT_ID`),
  KEY `IDX_INVENTORY_VARIANT` (`VARIANT_ID`),
  KEY `IDX_INVENTORY_REFERENCE` (`REFERENCE_TYPE`,`REFERENCE_ID`),
  CONSTRAINT `FK_INVENTORY_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANTS` (`VARIANT_ID`),
  CONSTRAINT `CHK_INVENTORY_CHANGE` CHECK ((`QUANTITY_CHANGE` <> 0)),
  CONSTRAINT `CHK_INVENTORY_MOVEMENT_TYPE` CHECK ((`MOVEMENT_TYPE` in (_utf8mb4'PURCHASE',_utf8mb4'SALE',_utf8mb4'CANCELLATION',_utf8mb4'RETURN',_utf8mb4'ADJUSTMENT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `LOGIN_ATTEMPTS` (
  `LOGIN_ATTEMPT_ID` bigint NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `IP_ADDRESS` varchar(45) DEFAULT NULL,
  `IS_SUCCESSFUL` tinyint(1) NOT NULL,
  `FAILURE_REASON` varchar(255) DEFAULT NULL,
  `ATTEMPTED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN_ATTEMPT_ID`),
  KEY `IDX_LOGIN_ATTEMPTS_EMAIL_TIME` (`EMAIL`,`ATTEMPTED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `MIGRATION_20260809_GENERAL_IMAGES` (
  `IMAGE_ID` bigint NOT NULL,
  PRIMARY KEY (`IMAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `NOTIFICATIONS` (
  `NOTIFICATION_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `NOTIFICATION_TYPE` varchar(30) NOT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `MESSAGE` text NOT NULL,
  `NOTIFICATION_STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `SENT_AT` datetime DEFAULT NULL,
  `READ_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`NOTIFICATION_ID`),
  KEY `IDX_NOTIFICATIONS_USER_STATUS` (`USER_ID`,`NOTIFICATION_STATUS`),
  CONSTRAINT `FK_NOTIFICATION_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_NOTIFICATION_STATUS` CHECK ((`NOTIFICATION_STATUS` in (_utf8mb4'PENDING',_utf8mb4'SENT',_utf8mb4'FAILED',_utf8mb4'READ'))),
  CONSTRAINT `CHK_NOTIFICATION_TYPE` CHECK ((`NOTIFICATION_TYPE` in (_utf8mb4'EMAIL',_utf8mb4'SMS',_utf8mb4'PUSH',_utf8mb4'IN_APP')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ORDER_ITEMS` (
  `ORDER_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `VARIANT_ID` bigint DEFAULT NULL,
  `PRODUCT_NAME` varchar(255) NOT NULL,
  `SKU` varchar(100) NOT NULL,
  `VARIANT_LABEL` varchar(255) DEFAULT NULL,
  `QUANTITY` int NOT NULL,
  `UNIT_PRICE` decimal(12,2) NOT NULL,
  `TAX_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `LINE_TOTAL` decimal(12,2) NOT NULL,
  PRIMARY KEY (`ORDER_ITEM_ID`),
  UNIQUE KEY `UQ_ORDER_VARIANT` (`ORDER_ID`,`VARIANT_ID`),
  KEY `IDX_ORDER_ITEMS_ORDER` (`ORDER_ID`),
  KEY `IDX_ORDER_ITEMS_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_ORDER_ITEM_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ORDER_ITEM_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANTS` (`VARIANT_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_ORDER_ITEM_AMOUNTS` CHECK (((`UNIT_PRICE` >= 0) and (`TAX_AMOUNT` >= 0) and (`DISCOUNT_AMOUNT` >= 0) and (`LINE_TOTAL` >= 0))),
  CONSTRAINT `CHK_ORDER_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ORDER_STATUS_HISTORY` (
  `ORDER_STATUS_HISTORY_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `OLD_STATUS` varchar(30) DEFAULT NULL,
  `NEW_STATUS` varchar(30) NOT NULL,
  `CHANGED_BY` bigint DEFAULT NULL,
  `NOTES` varchar(500) DEFAULT NULL,
  `CHANGED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_STATUS_HISTORY_ID`),
  KEY `FK_STATUS_HISTORY_USER` (`CHANGED_BY`),
  KEY `IDX_ORDER_STATUS_HISTORY_ORDER` (`ORDER_ID`),
  CONSTRAINT `FK_STATUS_HISTORY_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_STATUS_HISTORY_USER` FOREIGN KEY (`CHANGED_BY`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ORDERS` (
  `ORDER_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `SHIPPING_ADDRESS_ID` bigint DEFAULT NULL,
  `BILLING_ADDRESS_ID` bigint DEFAULT NULL,
  `COUPON_ID` bigint DEFAULT NULL,
  `ORDER_STATUS` varchar(30) NOT NULL DEFAULT 'PLACED',
  `SUBTOTAL_AMOUNT` decimal(12,2) NOT NULL,
  `DISCOUNT_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `TAX_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `SHIPPING_AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `TOTAL_AMOUNT` decimal(12,2) NOT NULL,
  `SHIPPING_NAME` varchar(255) NOT NULL,
  `SHIPPING_PHONE` varchar(20) DEFAULT NULL,
  `SHIPPING_ADDRESS_LINE_1` varchar(255) NOT NULL,
  `SHIPPING_ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `SHIPPING_CITY` varchar(100) NOT NULL,
  `SHIPPING_STATE` varchar(100) NOT NULL,
  `SHIPPING_PINCODE` varchar(20) NOT NULL,
  `SHIPPING_COUNTRY` varchar(100) NOT NULL,
  `PURCHASED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELIVERED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AUTO_OFFER_ID` bigint DEFAULT NULL,
  `AUTO_OFFER_NAME` varchar(120) DEFAULT NULL,
  `AUTO_OFFER_REQUIRED_QUANTITY` int DEFAULT NULL,
  `AUTO_OFFER_DISCOUNT_PER_GROUP` decimal(12,2) DEFAULT NULL,
  `AUTO_OFFER_ELIGIBLE_QUANTITY` int DEFAULT NULL,
  `AUTO_OFFER_GROUPS` int DEFAULT NULL,
  `AUTO_OFFER_DISCOUNT` decimal(12,2) DEFAULT NULL,
  `IDEMPOTENCY_KEY` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE KEY `UQ_ORDER_IDEMPOTENCY_KEY` (`IDEMPOTENCY_KEY`),
  KEY `FK_ORDER_SHIPPING_ADDRESS` (`SHIPPING_ADDRESS_ID`),
  KEY `FK_ORDER_BILLING_ADDRESS` (`BILLING_ADDRESS_ID`),
  KEY `FK_ORDER_COUPON` (`COUPON_ID`),
  KEY `IDX_ORDERS_USER` (`USER_ID`),
  KEY `IDX_ORDERS_STATUS` (`ORDER_STATUS`),
  KEY `IDX_ORDERS_PURCHASED_AT` (`PURCHASED_AT`),
  KEY `FK_ORDER_AUTO_OFFER` (`AUTO_OFFER_ID`),
  CONSTRAINT `FK_ORDER_AUTO_OFFER` FOREIGN KEY (`AUTO_OFFER_ID`) REFERENCES `AUTOMATIC_OFFERS` (`AUTOMATIC_OFFER_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_BILLING_ADDRESS` FOREIGN KEY (`BILLING_ADDRESS_ID`) REFERENCES `ADDRESSES` (`ADDRESS_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_COUPON` FOREIGN KEY (`COUPON_ID`) REFERENCES `COUPONS` (`COUPON_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_SHIPPING_ADDRESS` FOREIGN KEY (`SHIPPING_ADDRESS_ID`) REFERENCES `ADDRESSES` (`ADDRESS_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_ORDER_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
  CONSTRAINT `CHK_ORDER_AMOUNTS` CHECK (((`SUBTOTAL_AMOUNT` >= 0) and (`DISCOUNT_AMOUNT` >= 0) and (`TAX_AMOUNT` >= 0) and (`SHIPPING_AMOUNT` >= 0) and (`TOTAL_AMOUNT` >= 0))),
  CONSTRAINT `CHK_ORDER_STATUS` CHECK ((`ORDER_STATUS` in (_utf8mb4'PLACED',_utf8mb4'CONFIRMED',_utf8mb4'PROCESSING',_utf8mb4'SHIPPED',_utf8mb4'DELIVERED',_utf8mb4'CANCELLED',_utf8mb4'RETURNED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PASSWORD_RESET_TOKENS` (
  `PASSWORD_RESET_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `USED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PASSWORD_RESET_TOKEN_ID`),
  UNIQUE KEY `UQ_PASSWORD_RESET_TOKEN` (`TOKEN_HASH`),
  KEY `FK_PASSWORD_RESET_USER` (`USER_ID`),
  CONSTRAINT `FK_PASSWORD_RESET_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PAYMENTS` (
  `PAYMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `AMOUNT` decimal(12,2) NOT NULL,
  `PAYMENT_METHOD` varchar(50) NOT NULL,
  `PAYMENT_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `PAYMENT_PROVIDER` varchar(100) DEFAULT NULL,
  `PROVIDER_REFERENCE` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PAID_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  UNIQUE KEY `UQ_PAYMENT_PROVIDER_REFERENCE` (`PROVIDER_REFERENCE`),
  KEY `IDX_PAYMENTS_ORDER` (`ORDER_ID`),
  KEY `IDX_PAYMENTS_PROVIDER_REFERENCE` (`PROVIDER_REFERENCE`),
  KEY `IDX_PAYMENTS_ORDER_STATUS` (`ORDER_ID`,`PAYMENT_STATUS`),
  CONSTRAINT `FK_PAYMENT_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  CONSTRAINT `CHK_PAYMENT_AMOUNT` CHECK ((`AMOUNT` > 0)),
  CONSTRAINT `CHK_PAYMENT_STATUS` CHECK ((`PAYMENT_STATUS` in (_utf8mb4'PENDING',_utf8mb4'AUTHORIZED',_utf8mb4'PAID',_utf8mb4'FAILED',_utf8mb4'CANCELLED',_utf8mb4'PARTIALLY_REFUNDED',_utf8mb4'REFUNDED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PERMISSIONS` (
  `PERMISSION_ID` bigint NOT NULL AUTO_INCREMENT,
  `PERMISSION_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PERMISSION_ID`),
  UNIQUE KEY `UQ_PERMISSION_NAME` (`PERMISSION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PRODUCT_ATTRIBUTES` (
  `ATTRIBUTE_ID` bigint NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint NOT NULL,
  `VARIANT_ID` bigint DEFAULT NULL,
  `ATTRIBUTE_NAME` varchar(100) NOT NULL,
  `ATTRIBUTE_VALUE` varchar(255) NOT NULL,
  PRIMARY KEY (`ATTRIBUTE_ID`),
  UNIQUE KEY `UQ_PRODUCT_ATTRIBUTE` (`PRODUCT_ID`,`VARIANT_ID`,`ATTRIBUTE_NAME`,`ATTRIBUTE_VALUE`),
  KEY `IDX_PRODUCT_ATTRIBUTES_PRODUCT` (`PRODUCT_ID`),
  KEY `IDX_PRODUCT_ATTRIBUTES_VARIANT` (`VARIANT_ID`),
  CONSTRAINT `FK_ATTRIBUTE_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ATTRIBUTE_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANTS` (`VARIANT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PRODUCT_CATEGORIES` (
  `PRODUCT_ID` bigint NOT NULL,
  `CATEGORY_ID` bigint NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`,`CATEGORY_ID`),
  KEY `IDX_PRODUCT_CATEGORIES_CATEGORY` (`CATEGORY_ID`),
  CONSTRAINT `FK_PRODUCT_CATEGORY_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORIES` (`CATEGORY_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_PRODUCT_CATEGORY_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PRODUCT_IMAGES` (
  `IMAGE_ID` bigint NOT NULL AUTO_INCREMENT,
  `PUBLIC_ID` varchar(36) NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `VARIANT_ID` bigint DEFAULT NULL,
  `IMAGE_URL` varchar(2048) NOT NULL,
  `ALT_TEXT` varchar(255) DEFAULT NULL,
  `DISPLAY_ORDER` int NOT NULL DEFAULT '0',
  `IS_PRIMARY` tinyint(1) NOT NULL DEFAULT '0',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VARIANT_PRIMARY_SINGLETON` bigint GENERATED ALWAYS AS (if((`IS_PRIMARY` = 1),`VARIANT_ID`,NULL)) VIRTUAL,
  PRIMARY KEY (`IMAGE_ID`),
  UNIQUE KEY `UQ_PRODUCT_IMAGES_PUBLIC_ID` (`PUBLIC_ID`),
  UNIQUE KEY `UQ_PRODUCT_IMAGES_VARIANT_PRIMARY` (`VARIANT_PRIMARY_SINGLETON`),
  KEY `IDX_PRODUCT_IMAGES_PRODUCT` (`PRODUCT_ID`),
  KEY `IDX_PRODUCT_IMAGES_ORDER` (`PRODUCT_ID`,`DISPLAY_ORDER`,`IMAGE_ID`),
  KEY `IDX_PRODUCT_IMAGES_VARIANT` (`VARIANT_ID`,`DISPLAY_ORDER`),
  CONSTRAINT `FK_PRODUCT_IMAGE_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_PRODUCT_IMAGE_VARIANT` FOREIGN KEY (`VARIANT_ID`) REFERENCES `PRODUCT_VARIANTS` (`VARIANT_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_IMAGE_DISPLAY_ORDER` CHECK ((`DISPLAY_ORDER` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PRODUCT_VARIANTS` (
  `VARIANT_ID` bigint NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` bigint NOT NULL,
  `POSITION` int NOT NULL,
  `SKU` varchar(100) NOT NULL,
  `VARIANT_NAME` varchar(255) DEFAULT NULL,
  `VARIANT_DESCRIPTION` text,
  `PRICE` decimal(12,2) NOT NULL,
  `QUANTITY_AVAILABLE` int NOT NULL DEFAULT '0',
  `LOW_STOCK_THRESHOLD` int NOT NULL DEFAULT '5',
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`VARIANT_ID`),
  UNIQUE KEY `UQ_VARIANT_SKU` (`SKU`),
  UNIQUE KEY `UQ_PRODUCT_VARIANTS_POSITION` (`PRODUCT_ID`,`POSITION`),
  KEY `IDX_PRODUCT_VARIANTS_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_VARIANT_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_LOW_STOCK_THRESHOLD` CHECK ((`LOW_STOCK_THRESHOLD` >= 0)),
  CONSTRAINT `CHK_VARIANT_PRICE` CHECK ((`PRICE` >= 0)),
  CONSTRAINT `CHK_VARIANT_QUANTITY` CHECK ((`QUANTITY_AVAILABLE` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `PRODUCTS` (
  `PRODUCT_ID` bigint NOT NULL AUTO_INCREMENT,
  `TAX_RATE_ID` bigint DEFAULT NULL,
  `PRODUCT_NAME` varchar(255) NOT NULL,
  `SLUG` varchar(160) NOT NULL,
  `PRODUCT_DESCRIPTION` text,
  `BRAND` varchar(150) DEFAULT NULL,
  `BASE_PRICE` decimal(12,2) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `PUBLISHED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VERSION` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE KEY `UQ_PRODUCTS_SLUG` (`SLUG`),
  KEY `FK_PRODUCT_TAX_RATE` (`TAX_RATE_ID`),
  KEY `IDX_PRODUCTS_NAME` (`PRODUCT_NAME`),
  KEY `IDX_PRODUCTS_BRAND` (`BRAND`),
  KEY `IDX_PRODUCTS_PUBLISHED_AT` (`PUBLISHED_AT`),
  CONSTRAINT `FK_PRODUCT_TAX_RATE` FOREIGN KEY (`TAX_RATE_ID`) REFERENCES `TAX_RATES` (`TAX_RATE_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_PRODUCT_PRICE` CHECK ((`BASE_PRICE` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `REFRESH_TOKENS` (
  `REFRESH_TOKEN_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `TOKEN_HASH` varchar(255) NOT NULL,
  `EXPIRES_AT` datetime NOT NULL,
  `REVOKED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY_IP` varchar(45) DEFAULT NULL,
  `REPLACED_BY_TOKEN_HASH` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REFRESH_TOKEN_ID`),
  UNIQUE KEY `UQ_REFRESH_TOKEN_HASH` (`TOKEN_HASH`),
  KEY `IDX_REFRESH_TOKEN_USER` (`USER_ID`),
  KEY `IDX_REFRESH_TOKEN_EXPIRY` (`EXPIRES_AT`),
  CONSTRAINT `FK_REFRESH_TOKEN_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `REFUNDS` (
  `REFUND_ID` bigint NOT NULL AUTO_INCREMENT,
  `PAYMENT_ID` bigint NOT NULL,
  `RETURN_ID` bigint DEFAULT NULL,
  `REFUND_AMOUNT` decimal(12,2) NOT NULL,
  `REFUND_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `PROVIDER_REFERENCE` varchar(255) DEFAULT NULL,
  `REASON` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PROCESSED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`REFUND_ID`),
  KEY `FK_REFUND_RETURN` (`RETURN_ID`),
  KEY `IDX_REFUNDS_PAYMENT` (`PAYMENT_ID`),
  CONSTRAINT `FK_REFUND_PAYMENT` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENTS` (`PAYMENT_ID`),
  CONSTRAINT `FK_REFUND_RETURN` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURNS` (`RETURN_ID`) ON DELETE SET NULL,
  CONSTRAINT `CHK_REFUND_AMOUNT` CHECK ((`REFUND_AMOUNT` > 0)),
  CONSTRAINT `CHK_REFUND_STATUS` CHECK ((`REFUND_STATUS` in (_utf8mb4'PENDING',_utf8mb4'PROCESSING',_utf8mb4'COMPLETED',_utf8mb4'FAILED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `RETURN_ITEMS` (
  `RETURN_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `RETURN_ID` bigint NOT NULL,
  `ORDER_ITEM_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL,
  `ITEM_CONDITION` varchar(50) DEFAULT NULL,
  `RETURN_REASON` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RETURN_ITEM_ID`),
  UNIQUE KEY `UQ_RETURN_ORDER_ITEM` (`RETURN_ID`,`ORDER_ITEM_ID`),
  KEY `IDX_RETURN_ITEMS_ORDER_ITEM` (`ORDER_ITEM_ID`),
  CONSTRAINT `FK_RETURN_ITEM_ORDER_ITEM` FOREIGN KEY (`ORDER_ITEM_ID`) REFERENCES `ORDER_ITEMS` (`ORDER_ITEM_ID`),
  CONSTRAINT `FK_RETURN_ITEM_RETURN` FOREIGN KEY (`RETURN_ID`) REFERENCES `RETURNS` (`RETURN_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_RETURN_ITEM_QUANTITY` CHECK ((`QUANTITY` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `RETURNS` (
  `RETURN_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `USER_ID` bigint NOT NULL,
  `RETURN_STATUS` varchar(30) NOT NULL DEFAULT 'REQUESTED',
  `RETURN_REASON` varchar(255) NOT NULL,
  `CUSTOMER_COMMENTS` text,
  `ADMIN_COMMENTS` text,
  `REQUESTED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `APPROVED_AT` datetime DEFAULT NULL,
  `RECEIVED_AT` datetime DEFAULT NULL,
  `COMPLETED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`RETURN_ID`),
  KEY `IDX_RETURNS_ORDER` (`ORDER_ID`),
  KEY `IDX_RETURNS_USER` (`USER_ID`),
  CONSTRAINT `FK_RETURN_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  CONSTRAINT `FK_RETURN_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`),
  CONSTRAINT `CHK_RETURN_STATUS` CHECK ((`RETURN_STATUS` in (_utf8mb4'REQUESTED',_utf8mb4'APPROVED',_utf8mb4'REJECTED',_utf8mb4'PICKED_UP',_utf8mb4'RECEIVED',_utf8mb4'COMPLETED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `REVIEWS` (
  `REVIEW_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `ORDER_ITEM_ID` bigint DEFAULT NULL,
  `RATING` int NOT NULL,
  `REVIEW_TEXT` text,
  `REVIEW_STATUS` varchar(20) NOT NULL DEFAULT 'PENDING',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REVIEW_ID`),
  UNIQUE KEY `UQ_USER_ORDER_ITEM_REVIEW` (`USER_ID`,`ORDER_ITEM_ID`),
  KEY `FK_REVIEW_ORDER_ITEM` (`ORDER_ITEM_ID`),
  KEY `IDX_REVIEWS_PRODUCT_STATUS` (`PRODUCT_ID`,`REVIEW_STATUS`),
  CONSTRAINT `FK_REVIEW_ORDER_ITEM` FOREIGN KEY (`ORDER_ITEM_ID`) REFERENCES `ORDER_ITEMS` (`ORDER_ITEM_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_REVIEW_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_REVIEW_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  CONSTRAINT `CHK_REVIEW_RATING` CHECK ((`RATING` between 1 and 5)),
  CONSTRAINT `CHK_REVIEW_STATUS` CHECK ((`REVIEW_STATUS` in (_cp850'PUBLISHED',_cp850'PENDING',_cp850'APPROVED',_cp850'REJECTED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ROLE_PERMISSIONS` (
  `ROLE_ID` bigint NOT NULL,
  `PERMISSION_ID` bigint NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`PERMISSION_ID`),
  KEY `FK_ROLE_PERMISSION_PERMISSION` (`PERMISSION_ID`),
  CONSTRAINT `FK_ROLE_PERMISSION_PERMISSION` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSIONS` (`PERMISSION_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_ROLE_PERMISSION_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ROLE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `ROLES` (
  `ROLE_ID` bigint NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `UQ_ROLE_NAME` (`ROLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `SHIPMENTS` (
  `SHIPMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint NOT NULL,
  `SHIPPING_PROVIDER` varchar(100) DEFAULT NULL,
  `TRACKING_NUMBER` varchar(255) DEFAULT NULL,
  `SHIPMENT_STATUS` varchar(30) NOT NULL DEFAULT 'PENDING',
  `SHIPPED_AT` datetime DEFAULT NULL,
  `EXPECTED_DELIVERY_AT` datetime DEFAULT NULL,
  `DELIVERED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SHIPMENT_ID`),
  KEY `IDX_SHIPMENTS_ORDER` (`ORDER_ID`),
  KEY `IDX_SHIPMENTS_TRACKING` (`TRACKING_NUMBER`),
  CONSTRAINT `FK_SHIPMENT_ORDER` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  CONSTRAINT `CHK_SHIPMENT_STATUS` CHECK ((`SHIPMENT_STATUS` in (_utf8mb4'PENDING',_utf8mb4'PACKED',_utf8mb4'SHIPPED',_utf8mb4'IN_TRANSIT',_utf8mb4'OUT_FOR_DELIVERY',_utf8mb4'DELIVERED',_utf8mb4'FAILED',_utf8mb4'RETURNED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `TAX_RATES` (
  `TAX_RATE_ID` bigint NOT NULL AUTO_INCREMENT,
  `TAX_NAME` varchar(100) NOT NULL,
  `COUNTRY` varchar(100) DEFAULT NULL,
  `STATE` varchar(100) DEFAULT NULL,
  `RATE_PERCENT` decimal(7,4) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `VALID_FROM` datetime DEFAULT NULL,
  `VALID_TO` datetime DEFAULT NULL,
  PRIMARY KEY (`TAX_RATE_ID`),
  CONSTRAINT `CHK_TAX_RATE` CHECK ((`RATE_PERCENT` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `USER_ROLES` (
  `USER_ID` bigint NOT NULL,
  `ROLE_ID` bigint NOT NULL,
  `ASSIGNED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `FK_USER_ROLE_ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_USER_ROLE_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLES` (`ROLE_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_USER_ROLE_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `USERS` (
  `USER_ID` bigint NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(255) NOT NULL,
  `PASSWORD_HASH` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `EMAIL_VERIFIED` tinyint(1) NOT NULL DEFAULT '0',
  `ACCOUNT_LOCKED` tinyint(1) NOT NULL DEFAULT '0',
  `FAILED_LOGIN_ATTEMPTS` int NOT NULL DEFAULT '0',
  `LOCKED_UNTIL` datetime DEFAULT NULL,
  `PASSWORD_CHANGED_AT` datetime DEFAULT NULL,
  `LAST_LOGIN_AT` datetime DEFAULT NULL,
  `VERSION` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UQ_USERS_EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `WISHLIST_ITEMS` (
  `WISHLIST_ITEM_ID` bigint NOT NULL AUTO_INCREMENT,
  `WISHLIST_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `ADDED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WISHLIST_ITEM_ID`),
  UNIQUE KEY `UQ_WISHLIST_PRODUCT` (`WISHLIST_ID`,`PRODUCT_ID`),
  KEY `FK_WISHLIST_ITEM_PRODUCT` (`PRODUCT_ID`),
  CONSTRAINT `FK_WISHLIST_ITEM_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_WISHLIST_ITEM_WISHLIST` FOREIGN KEY (`WISHLIST_ID`) REFERENCES `WISHLISTS` (`WISHLIST_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `WISHLISTS` (
  `WISHLIST_ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `WISHLIST_NAME` varchar(100) NOT NULL DEFAULT 'DEFAULT',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`WISHLIST_ID`),
  UNIQUE KEY `UQ_USER_WISHLIST` (`USER_ID`,`WISHLIST_NAME`),
  CONSTRAINT `FK_WISHLIST_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;



/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `ROLES` WRITE;
/*!40000 ALTER TABLE `ROLES` DISABLE KEYS */;
INSERT IGNORE INTO `ROLES` (`ROLE_ID`, `ROLE_NAME`, `DESCRIPTION`) VALUES (1,'CUSTOMER','Regular e-commerce customer');
INSERT IGNORE INTO `ROLES` (`ROLE_ID`, `ROLE_NAME`, `DESCRIPTION`) VALUES (2,'ADMIN','Full system administrator');
INSERT IGNORE INTO `ROLES` (`ROLE_ID`, `ROLE_NAME`, `DESCRIPTION`) VALUES (3,'SUPPORT','Customer support employee');
INSERT IGNORE INTO `ROLES` (`ROLE_ID`, `ROLE_NAME`, `DESCRIPTION`) VALUES (4,'INVENTORY_MANAGER','Manages products and inventory');
/*!40000 ALTER TABLE `ROLES` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `PERMISSIONS` WRITE;
/*!40000 ALTER TABLE `PERMISSIONS` DISABLE KEYS */;
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (1,'PRODUCT_READ','View products');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (2,'PRODUCT_WRITE','Create and update products');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (3,'PRODUCT_DELETE','Delete products');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (4,'ORDER_CREATE','Place an order');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (5,'ORDER_READ_OWN','View own orders');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (6,'ORDER_READ_ALL','View every order');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (7,'ORDER_UPDATE','Update order status');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (8,'USER_READ','View user details');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (9,'USER_UPDATE','Update user details');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (10,'RETURN_CREATE','Request a return');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (11,'RETURN_MANAGE','Approve or reject returns');
INSERT IGNORE INTO `PERMISSIONS` (`PERMISSION_ID`, `PERMISSION_NAME`, `DESCRIPTION`) VALUES (12,'INVENTORY_MANAGE','Manage inventory');
/*!40000 ALTER TABLE `PERMISSIONS` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `ROLE_PERMISSIONS` WRITE;
/*!40000 ALTER TABLE `ROLE_PERMISSIONS` DISABLE KEYS */;
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (1,1);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,1);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (3,1);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (4,1);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,2);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (4,2);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,3);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (1,4);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,4);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (1,5);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,5);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,6);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (3,6);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,7);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (3,7);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,8);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (3,8);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (1,9);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,9);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (1,10);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,10);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,11);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (3,11);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (2,12);
INSERT IGNORE INTO `ROLE_PERMISSIONS` (`ROLE_ID`, `PERMISSION_ID`) VALUES (4,12);
/*!40000 ALTER TABLE `ROLE_PERMISSIONS` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `CATEGORIES` WRITE;
/*!40000 ALTER TABLE `CATEGORIES` DISABLE KEYS */;
INSERT IGNORE INTO `CATEGORIES` (`CATEGORY_ID`, `PARENT_CATEGORY_ID`, `CATEGORY_NAME`, `DESCRIPTION`, `IS_ACTIVE`, `CREATED_AT`) VALUES (1,NULL,'Men','Eyewear designed for men',1,'2026-08-02 19:19:09');
INSERT IGNORE INTO `CATEGORIES` (`CATEGORY_ID`, `PARENT_CATEGORY_ID`, `CATEGORY_NAME`, `DESCRIPTION`, `IS_ACTIVE`, `CREATED_AT`) VALUES (2,NULL,'Women','Eyewear designed for women',1,'2026-08-02 19:19:09');
INSERT IGNORE INTO `CATEGORIES` (`CATEGORY_ID`, `PARENT_CATEGORY_ID`, `CATEGORY_NAME`, `DESCRIPTION`, `IS_ACTIVE`, `CREATED_AT`) VALUES (3,NULL,'Unisex','Eyewear designed for everyone',1,'2026-08-02 19:19:09');
INSERT IGNORE INTO `CATEGORIES` (`CATEGORY_ID`, `PARENT_CATEGORY_ID`, `CATEGORY_NAME`, `DESCRIPTION`, `IS_ACTIVE`, `CREATED_AT`) VALUES (4,NULL,'Accessory','Eyewear accessories and care products',1,'2026-08-02 19:19:09');
/*!40000 ALTER TABLE `CATEGORIES` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `USERS` WRITE;
/*!40000 ALTER TABLE `USERS` DISABLE KEYS */;
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (1,'admin@example.com','$2a$12$6Rig3nGp/EAXAUpeX/qTcO1WkRPJrvmrKeQUeeZp6ml3wKNzrNRGe','Store Admin',NULL,1,'2026-08-01 07:28:20','2026-08-10 17:07:20',0,0,0,NULL,'2026-08-10 17:07:20','2026-08-10 17:07:03',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (2,'customer@example.com','$2a$12$ujDeYAfpU./hZ4wd7ik8j.58HPHBMryy7BA81UjZtHsWDLtDDtbPS','Test Customer','9876543210',1,'2026-08-01 09:51:18','2026-08-01 18:41:18',0,0,0,NULL,'2026-08-01 09:51:18','2026-08-01 18:41:18',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (3,'bhuvan.sharma.bits24@gmail.com','$2a$12$Wr5mkMEQKGbX6B/9/uJmrOo91Gow6TTdg1QspnErrPVXlAbGRryGO','Bhuvan Sharma','8252264893',1,'2026-08-02 11:34:52','2026-08-10 16:42:07',1,0,0,NULL,'2026-08-10 16:42:07','2026-08-10 16:41:41',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (4,'iambhuvan0987@gmail.com','$2a$12$wdyNk6E0LTnTlTSsCjfSsO9LzGDffW7orHYRRqvek8ulSshtwHg9e','Jefff','9001807536',1,'2026-08-03 21:43:32','2026-08-10 17:55:16',1,0,0,NULL,'2026-08-10 17:55:16','2026-08-10 17:07:26',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (5,'iambhuvanmod@gmail.com','$2a$12$UgT17hXTkLynpzaruoxCEOSXD6nmjYv9Mya.CBlpTpvzCdmBuk0Xy','Jeff Besos','898097',1,'2026-08-04 14:42:41','2026-08-04 14:45:23',1,0,0,NULL,'2026-08-04 14:42:41','2026-08-04 14:42:41',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (7,'iambhuvan0987c@gmail.com','$2a$12$MK0tSlRLbSaa5CKbV2QgF.XUcCPk9X22w0lTIfVjRs4zHK5Ml8IPm','Bhuvan Sharma','+919001807536',1,'2026-08-06 17:14:37','2026-08-06 17:14:37',0,0,0,NULL,'2026-08-06 17:14:37',NULL,0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (8,'dklord2469@gmail.com','$2a$12$sUyUYYInbNOwEr8dist1Oe7nBQkN7r2gkqVCOUR5QQg4PjP2r2.Iq','Dark Lord',NULL,1,'2026-08-09 15:03:22','2026-08-09 16:00:06',1,0,0,NULL,'2026-08-09 16:00:06','2026-08-09 15:03:22',0);
INSERT IGNORE INTO `USERS` (`USER_ID`, `EMAIL`, `PASSWORD_HASH`, `NAME`, `PHONE_NUMBER`, `IS_ACTIVE`, `CREATED_AT`, `UPDATED_AT`, `EMAIL_VERIFIED`, `ACCOUNT_LOCKED`, `FAILED_LOGIN_ATTEMPTS`, `LOCKED_UNTIL`, `PASSWORD_CHANGED_AT`, `LAST_LOGIN_AT`, `VERSION`) VALUES (9,'gojosatoruisalive6868@gmail.com','$2a$12$RW/0uymFXk/44Gkp.S./p./Clb3gkOBDDDAPkb0Z2IKB8kix6PwjC','Dark Lord','+918252264893',1,'2026-08-10 16:21:50','2026-08-10 17:57:05',1,0,0,NULL,'2026-08-10 16:41:23','2026-08-10 17:57:05',0);
/*!40000 ALTER TABLE `USERS` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `USER_ROLES` WRITE;
/*!40000 ALTER TABLE `USER_ROLES` DISABLE KEYS */;
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (1,1,'2026-08-01 12:58:20');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (1,2,'2026-08-01 13:32:32');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (2,1,'2026-08-01 15:21:18');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (3,1,'2026-08-02 17:04:52');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (4,1,'2026-08-04 03:13:32');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (5,1,'2026-08-04 20:12:40');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (7,1,'2026-08-06 22:44:36');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (8,1,'2026-08-09 20:33:21');
INSERT IGNORE INTO `USER_ROLES` (`USER_ID`, `ROLE_ID`, `ASSIGNED_AT`) VALUES (9,1,'2026-08-10 21:51:50');
/*!40000 ALTER TABLE `USER_ROLES` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;



